company_name: Freehold Cottage
title: Freehold Cottage Residential Home
description: Residential Care Home in Shawforth, Rochdale
domain: "https://www.freeholdcottage.com"

# you can leave any of these empty - that bit just won't show 

email_address: freeholdcottage@gmail.com
phone_number: 01706 853384

# if you blank this it'll remove the whatsapp links
# whatsapp_country_code: 44

address:
  street: 452 Market St
  locality: Shawforth, Rochdale
  region: Lancashire
  post_code: OL12 8JB
  country: United Kingdom

geo:
  latitude: 53.6845915958082
  longitude: -2.166006644012877

# https://schema.org/
json_ld:
  type: LocalBusiness
  description: "Freehold Cottage Residential Home"
  country_code: 44
google_maps: https://goo.gl/maps/8xbF4cJMCJjX9Vee6
google_maps_embed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2362.8911053200522!2d-2.1682167843129148!3d53.68456618005128!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487bbe7a7e728fdb%3A0xb8b600deb70cdf9e!2s452%20Market%20St%2C%20Shawforth%2C%20Rochdale%20OL12%208JB!5e0!3m2!1sen!2suk!4v1630289871024!5m2!1sen!2suk"

# you probably don't need to touch much below here that often

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 80
  strip: true
  output_path_format: resized/%{width}/%{dirname}/%{basename}
  extra_images:
    - assets/news/*/*.jpg
    - assets/banner.jpg
    - assets/flower-background.png
  sizes:
    - width: 200
    - width: 400
    - width: 800
    - width: 1200

env: production

markdown: kramdown

plugins:
  - jekyll-responsive-image

collections:
  pages:
    output: true
  services:
    output: true
  news:
    output: true

defaults:
  - scope:
      path: "_pages"
    values:
      layout: page
      permalink: :slug
  - scope:
      type: services
    values:
      permalink: services/:title
      layout: service
  - scope:
      path: "assets/services"
    values:
      service_image: true